user_interaction/hello/urls.py
from django.urls import path
from . import views

app_name = 'hello'
urlpatterns = [
    path('<str:name>/', views.greet, name='greet'),
    path('', views.askName, name='ask'),
]

user_interaction/user_interaction/urls.py
from django.contrib import admin
from django.urls import path, include
from hello import views as hello_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', hello_views.tasks, name='tasks'),
    path('', include('hello.urls')),
]

user_interaction/hello/models.py
from django.db import models

# Create your models here.

user_interaction/hello/forms.py
from django import forms

class NameForm(forms.Form):
    name = forms.CharField(max_length=64)

user_interaction/hello/views.py
from django.shortcuts import render, redirect
from .forms import NameForm

# Create your views here.
def greet(request, name):
    return render(request, 'hello/greet.html', {'name':name.capitalize})

def askName(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            return redirect('hello:greet', name=name)
    return render(request, 'hello/ask.html', {'form':NameForm})


def tasks(request):
    task = ''
    if request.method == 'POST':
        task = request.POST['task'].capitalize()
        print(task)
    return render(request, 'hello/tasks.html', {'task': task})

user_interaction/hello/templates/hello/ask.html
{% extends 'hello/base.html' %}
{% load static %}

{% block title %}Hello, Django{% endblock %}

{% block body %}

<link rel="stylesheet" type="text/css" href="{% static '/hello/css/hello.css' %}">
<h1>Enter your name</h1>
<form method="POST" action="{% url 'hello:ask' %}">
    {% csrf_token %}
    {{form}}
    <div class="btn-div"><button type="submit">Say Hello</button></div>
</form>

{% endblock %}

user_interaction/hello/templates/hello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <!-- <h1>Greeting Childen.</h1> -->
    {% block body %}{% endblock %}
</body>
</html>

user_interaction/hello/templates/hello/greet.html
{% extends 'hello/base.html' %}
{% load static %}

{% block title %}Hello, Django{% endblock %}

{% block body %}

<link rel="stylesheet" type="text/css" href="{% static '/hello/css/hello.css' %}">
<h1>Hello, {{name}}</h1>
<a href="{% url 'hello:ask' %}">What's Your name?</a>
{% endblock %}

user_interaction/hello/templates/hello/tasks.html
{% extends 'hello/base.html' %}
{% load static %}

{% block title %}Tasks Pile{% endblock %}

{% block body %}

<link rel="stylesheet" type="text/css" href="{% static '/hello/css/hello.css' %}">
<h1>Tasks Pile</h1>
<form method="POST" action="{% url 'tasks' %}">
    {% csrf_token %}
    <input type="text" autofocus name="task" placeholder="Add a Task">
    <div class="btn-div"><button type="submit">Add Task</button></div>
</form>

<h3>{{task}}</h3>

{% endblock %}